# Generated by Django 5.1.1 on 2024-09-12 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Fevrier'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Aout'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Decembre')], default='Janvier', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VolumeMutalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=200)),
                ('volume_gasoil', models.FloatField()),
                ('volume_essence', models.FloatField()),
                ('volume_petrol', models.FloatField()),
                ('annee', models.IntegerField(max_length=4)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('mois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.moismodel')),
            ],
        ),
    ]
