# Generated by Django 5.1.1 on 2024-09-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumemutalise',
            name='mois',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Fevrier'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Aout'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Decembre')], default='Janvier', max_length=10),
        ),
        migrations.AlterField(
            model_name='volumemutalise',
            name='annee',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='MoisModel',
        ),
    ]
