# Generated by Django 5.1.1 on 2024-09-12 11:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_volumemutalise_volume_essence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumemutalise',
            name='volume_essence',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='volumemutalise',
            name='volume_gasoil',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='volumemutalise',
            name='volume_petrol',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
    ]
